version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount data directory for development
      - ./data:/app/data:ro
      # Mount models directory for development
      - ./models:/app/models:ro
      # Mount app directory for hot reloading (optional)
      - ./app:/app/app:ro
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a simple database if needed later
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data:
