services:
  - type: web
    name: emotion-detection-backend
    env: python
    pythonVersion: "3.11"
    buildCommand: |
      # Ensure we're using Python 3.11
      python3.11 --version
      python3.11 -m pip install --upgrade pip
      python3.11 -m pip install -r requirements.txt
    startCommand: python3.11 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    autoDeploy: true
    instanceType: standard-1x
    # Force Python 3.11 environment
    buildFilter:
      paths:
        - backend/**
